/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.13
 * Generated at: 2019-05-01 19:21:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.Format;
import java.sql.ResultSet;
import java.sql.Statement;
import com.connection.*;
import java.sql.Connection;

public final class ProfileShow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.connection");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.Format");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>User Dashboard</title>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css1/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css1/bootstrap-responsive.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css1/uniform.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css1/select2.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css1/matrix-style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css1/matrix-media.css\" />\r\n");
      out.write("<link href=\"font-awesome/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!--Header-part-->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("  <h4>Admin Dashboard</h4>\r\n");
      out.write("  <!-- <h1><a href=\"dashboard.html\">Admin Dashboard</a></h1> -->\r\n");
      out.write("</div>\r\n");
      out.write("<!--close-Header-part--> \r\n");
      out.write("\r\n");
      out.write("<!--top-Header-menu-->\r\n");
      out.write("<div id=\"user-nav\" class=\"navbar navbar-inverse\">\r\n");
      out.write("  <ul class=\"nav\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <li class=\"\"><a title=\"\" href=\"logout.jsp\"><i class=\"icon icon-share-alt\"></i> \r\n");
      out.write("    <span style=\"color: white; font-size: 15px\" class=\"text\">Logout</span></a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--sidebar-menu-->\r\n");
      out.write("\r\n");
      out.write("<div id=\"sidebar\"> <a href=\"#\" class=\"visible-phone\"><i class=\"icon icon-th\"></i>Admin</a>\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "adminmenu.jsp", out, true);
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("  <div id=\"content-header\">\r\n");
      out.write("    <div id=\"breadcrumb\"> <a href=\"UserView.jsp\" title=\"Go to Home\" class=\"tip-bottom\"><i class=\"icon-home\"></i> \r\n");
      out.write("    Home</a>> <a href=\"#\" class=\"current\">Candidate Profile Show</a> </div>\r\n");
      out.write("   \r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <hr>\r\n");
      out.write("    <div class=\"row-fluid\">\r\n");
      out.write("      <div class=\"span12\">\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"widget-box\">\r\n");
      out.write("          <div class=\"widget-title\"> <span class=\"icon\"> <i class=\"icon-th\"></i> </span>\r\n");
      out.write("            <h5> View Profile </h5>\r\n");
      out.write("            <!-- <span class=\"label label-info\"> </span> --> </div>\r\n");
      out.write("          <div class=\"widget-content \">\r\n");
      out.write("          \r\n");
      out.write("            <form enctype=\"multipart/form-data\"  role=\"form\" action=\"Download\">\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<table style=\"width: 100%;font-size:20px;\" border=\"1\">\r\n");
      out.write("\t       <tr>\r\n");
      out.write("\t\t\t<td width=\"5%\"><h3>ID</h3> </td>\r\n");
      out.write("\t\t\t<td width=\"18%\"><h3>Date</h3> </td>\r\n");
      out.write("\t\t\t<td width=\"18%\"><h3>Name</h3> </td>\r\n");
      out.write("\t\t\t<td width=\"18%\"><h3>PanCard_No</h3> </td>\r\n");
      out.write("\t\t\t<td width=\"18%\"><h3>Gender</h3> </td>\r\n");
      out.write("\t\t\t<td width=\"18%\"><h3>Designation</h3> </td>\r\n");
      out.write("\t\t\t<td width=\"18%\"><h3>Email_ID</h3> </td>\r\n");
      out.write("\t\t\t<td width=\"18%\"><h3>Mobile</h3> </td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   ");
 
        	Connection connection = DBConnection.getConnection();
            Statement statement = connection.createStatement();
        
            ResultSet resultset =statement.executeQuery("select * from tblngoprofile ") ; 
          //  ResultSet resultset =statement.executeQuery("select * from candidateprofile ") ; 
			while(resultset.next())
             {
       		 
      out.write("\t\r\n");
      out.write("       \t\t <tr>\r\n");
      out.write("           \r\n");
      out.write("              <td> ");
      out.print( resultset.getString(1) );
      out.write(" </td>\r\n");
      out.write("               <td> ");
      out.print( resultset.getString(2) );
      out.write(" </td>\r\n");
      out.write("                 <td> ");
      out.print( resultset.getString(3) );
      out.write(" </td>\r\n");
      out.write("                  <td> ");
      out.print( resultset.getString(4) );
      out.write(" </td>\r\n");
      out.write("                   <td> ");
      out.print( resultset.getString(5) );
      out.write(" </td>\r\n");
      out.write("                    <td> ");
      out.print( resultset.getString(6) );
      out.write(" </td>\r\n");
      out.write("                    <td> ");
      out.print( resultset.getString(7) );
      out.write(" </td>\r\n");
      out.write("                    <td> ");
      out.print( resultset.getString(8) );
      out.write(" </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("       \t\t  ");
 
             } 
              
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form> \t\t\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("<!--Footer-part-->\r\n");
      out.write("<div class=\"row-fluid\">\r\n");
      out.write("  <div id=\"footer\" class=\"span12\">  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--end-Footer-part-->\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script> \r\n");
      out.write("<script src=\"js/jquery.ui.custom.js\"></script> \r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script> \r\n");
      out.write("<script src=\"js/jquery.uniform.js\"></script> \r\n");
      out.write("<script src=\"js/select2.min.js\"></script> \r\n");
      out.write("<script src=\"js/jquery.dataTables.min.js\"></script> \r\n");
      out.write("<script src=\"js/matrix.js\"></script> \r\n");
      out.write("<script src=\"js/matrix.tables.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
